### ISSUE TITLE
Error when trying to change the URL using the config command

### ISSUE THREAD

**Issue by ovidiupruteanu** [clns/izip-client#1]
[sitestacker.crossworld.org@virtualmina import]$ izip config url https://izip.pw
Error: user: Current not implemented on linux/amd64

**Comment by clns** [comment]
Apparently [os/user uses CGO](https://github.com/golang/go/issues/6376), thus the binaries can't be cross compiled from one platform. The commit 377b540dc74420417489c683e50cf5e563dd69da added docker support for cross compiling the binaries.
